### ISSUE TITLE
Publish on elementary OS 6

### ISSUE THREAD

**Issue by ryonakano** [alexkdeveloper/dfc#2]
Hi @alexkdeveloper!

I really interested in this app and would like to see it in AppCenter on elementary OS 6. However, it does not seem to be developed frequently these days. Are you still interested in releasing it for elementary OS 6?

**Comment by alexkdeveloper** [comment]
Hi! Yes, I am interested! But now there is little time to engage in publishing.

**Comment by ryonakano** [comment]
Nice! I'd like to help you publish the app then 😊

**Comment by alexkdeveloper** [comment]
Hi! The application was added pull request to the repository "elementary/appcenter-reviews". No one was looking this time. That was 2 days ago.
